# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-03-09 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190309_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='face_array',
            field=models.TextField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='face_image',
            field=models.ImageField(unique=True, upload_to='images/profile'),
        ),
    ]
