# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-03-09 21:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_profileimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faceimage',
            name='student',
        ),
        migrations.DeleteModel(
            name='FaceImage',
        ),
    ]
