# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-03-09 22:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20190309_2113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('articleID', models.AutoField(primary_key=True, serialize=False)),
                ('authorName', models.CharField(max_length=128)),
                ('articleTitle', models.CharField(max_length=128)),
                ('articleContent', models.TextField()),
                ('articlecopyContent', models.TextField()),
                ('article_copy_rate', models.FloatField()),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Student')),
            ],
        ),
    ]
