# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-03-10 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20190310_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='TmpImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/tmp')),
            ],
        ),
        migrations.AlterField(
            model_name='profileimage',
            name='image',
            field=models.ImageField(upload_to='images/profile'),
        ),
    ]
