# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-03-11 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20190310_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='old_volunteer',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='visitimage',
            name='string_array',
            field=models.TextField(default='', unique=True),
        ),
    ]
