# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-03-11 22:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20190311_0824'),
    ]

    operations = [
        migrations.CreateModel(
            name='SportImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(unique=True, upload_to='images/sport')),
                ('s_time', models.DateTimeField(unique=True)),
                ('number', models.FloatField()),
                ('content', models.TextField(unique=True)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Student')),
            ],
        ),
    ]
