# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-03-12 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20190312_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitimage',
            name='string_array',
            field=models.TextField(default='', unique=True),
        ),
    ]
