# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-03-12 20:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20190312_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sportimage',
            name='content',
        ),
    ]
