# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-03-12 20:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_sportimage_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(unique=True, upload_to='images/vol')),
                ('time_number', models.FloatField()),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='old_volunteer',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='student',
            name='volunteer',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='volunteerimage',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Student'),
        ),
    ]
