# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-03-13 00:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20190312_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='authorName',
        ),
    ]
